### ISSUE TITLE
FYI, I made a copy of Swordle

### ISSUE THREAD

**Issue by soderlind** [krawaller/swordle#2]
Ordle, a copy of Swordle, is at https://github.com/soderlind/ordle

And, btw, I'm still learning a lot from reading the Swordle source code. It's nicely done :)

Vennlig hilsen, 
Per

**Comment by litenjacob** [comment]
Hey Per! Thanks for the kind words! Nice work on the fork 🎉  I especially like that you added a small explanation of how to game actually works, which I haven't done yet 🙈 🙇
